// mobile/src/constants/emojis.ts

export const EMOJI = {
  HOME: "🏠",
  GESTAO: "🛠️",
  DIAGNOSTICO: "🧾",
  PUBLICACOES: "📚",
  NOTICIAS: "📢",
  ANIVERSARIOS: "🎂",
  LOGISTICA: "🚚",
  ASSEMBLEIA: "🗳️",
  REPASSE: "💱",
  FILIADOS: "👥",
  CONFIG: "⚙️",
  ESTATUTO: "📜",
  MEUS_DADOS: "👤",
  RESSARCIMENTO: "💸",
  JOGOS: "🏆",
  SEGURANCA: "🔒",
  ATUALIZACOES: "🔄",
  RELATORIOS: "📊",
  ESTATISTICAS: "📈",
  CONSULTA_PROCESSUAL: "⚖️",
  NOTIFICACOES: "📢",
  ENQUETES: "🗨️",
  NOVO_FILIADO: "👤",
  FECHAR_APP: "🔒",
  SAIR: "🚪",
  CONVENIOS: "🤝",
  CMS: "🌐",
};
