export const MODALIDADES_JOGOS_2026 = [
    { id: 'atletismo_100m_masc', label: '100m Masculino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_100m_fem', label: '100m Feminino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_400m_masc', label: '400m Masculino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_400m_fem', label: '400m Feminino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_1500m_masc', label: '1500m Masculino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_1500m_fem', label: '1500m Feminino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_5000m_masc', label: '5000m Masculino', grupo: 'Atletismo', pontuavel: true },
    { id: 'atletismo_5000m_fem', label: '5000m Feminino', grupo: 'Atletismo', pontuavel: true },
    { id: 'beach_tenis_dupla_livre', label: 'Beach Tênis - Dupla Livre', grupo: 'Beach Tênis', pontuavel: true },
    { id: 'beach_tenis_dupla_mista', label: 'Beach Tênis - Dupla Mista', grupo: 'Beach Tênis', pontuavel: true },
    { id: 'canastra', label: 'Canastra', grupo: 'Jogos de Mesa', pontuavel: true },
    { id: 'domino', label: 'Dominó', grupo: 'Jogos de Mesa', pontuavel: true },
    { id: 'truco_duplas', label: 'Truco (Duplas)', grupo: 'Jogos de Mesa', pontuavel: true },
    { id: 'xadrez', label: 'Xadrez', grupo: 'Jogos de Mesa', pontuavel: true },
    { id: 'futebol_society_livre', label: 'Futebol Society (Livre)', grupo: 'Futebol', pontuavel: true },
    { id: 'futebol_society_master', label: 'Futebol Society (Master - Acima de 55 anos)', grupo: 'Futebol', pontuavel: true },
    { id: 'futsal_livre', label: 'Futsal (Livre)', grupo: 'Futebol', pontuavel: true },
    { id: 'futevolei', label: 'Futevôlei', grupo: 'Vôlei', pontuavel: true },
    { id: 'voleibol_livre', label: 'Voleibol (Livre)', grupo: 'Vôlei', pontuavel: true },
    { id: 'voleibol_praia_dupla_masc', label: 'Vôlei de Praia - Dupla Masculina', grupo: 'Vôlei', pontuavel: true },
    { id: 'voleibol_praia_dupla_mista', label: 'Vôlei de Praia - Dupla Mista', grupo: 'Vôlei', pontuavel: true },
    { id: 'jiu_jitsu', label: 'Jiu-Jitsu', grupo: 'Artes Marciais', pontuavel: true },
    { id: 'natacao_50m_livre_masc', label: '50m Nado Livre (Masculino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_livre_fem', label: '50m Nado Livre (Feminino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_costas_masc', label: '50m Nado Costas (Masculino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_costas_fem', label: '50m Nado Costas (Feminino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_peito_masc', label: '50m Nado Peito (Masculino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_peito_fem', label: '50m Nado Peito (Feminino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_borboleta_masc', label: '50m Nado Borboleta (Masculino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_50m_borboleta_fem', label: '50m Nado Borboleta (Feminino)', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_revezamento_4x50m_livre', label: 'Revezamento 4x50m Livre', grupo: 'Natação', pontuavel: true },
    { id: 'natacao_revezamento_2x50m_misto', label: 'Revezamento 2x50 Misto', grupo: 'Natação', pontuavel: true },
    { id: 'sinuca_individual', label: 'Sinuca Individual', grupo: 'Sinuca', pontuavel: true },
    { id: 'sinuca_duplas', label: 'Sinuca Duplas', grupo: 'Sinuca', pontuavel: true },
    { id: 'tenis_quadra_individual_masc', label: 'Tênis de Quadra - Individual (Masculino)', grupo: 'Tênis', pontuavel: true },
    { id: 'tenis_quadra_duplas_livre', label: 'Tênis de Quadra - Duplas (Livre)', grupo: 'Tênis', pontuavel: true },
    { id: 'tenis_mesa_masc', label: 'Tênis de Mesa (Masculino)', grupo: 'Tênis de Mesa', pontuavel: true },
    { id: 'tenis_mesa_fem', label: 'Tênis de Mesa (Feminino)', grupo: 'Tênis de Mesa', pontuavel: true },
    { id: 'tenis_mesa_duplas', label: 'Tênis de Mesa (Duplas)', grupo: 'Tênis de Mesa', pontuavel: true },
    { id: 'tiro_nra_masc', label: 'Tiro NRA (Masculino)', grupo: 'Tiro', pontuavel: true },
    { id: 'tiro_nra_fem', label: 'Tiro NRA (Feminino)', grupo: 'Tiro', pontuavel: true },
    { id: 'tiro_ispc_masc', label: 'Tiro ISPC (Masculino)', grupo: 'Tiro', pontuavel: true },
    { id: 'tiro_ispc_fem', label: 'Tiro ISPC (Feminino)', grupo: 'Tiro', pontuavel: true },
    { id: 'peteca', label: 'Peteca', grupo: 'Exibição', pontuavel: false },
    { id: 'damas', label: 'Damas', grupo: 'Exibição', pontuavel: false },
    { id: 'bocha', label: 'Bocha', grupo: 'Exibição', pontuavel: false },
];
