// src/config/roles.config.js
module.exports = {
  ADMIN: ["*"],

  DIRETORIA: [
    "EDIT_FILIADO", "VIEW_ALL", "JOGOS_GERENCIAR", "VIEW_SELF", "EDIT_SELF",
    "VOTACAO_GERENCIAR", "VOTACAO_VOTAR"
  ],

  FUNCIONARIO: [
    "EDIT_FILIADO", "VIEW_ALL", "VIEW_SELF", "EDIT_SELF",
    "VOTACAO_VOTAR"
  ],

  ORGANIZADOR: [
    "JOGOS_GERENCIAR", "VIEW_INSCRICOES", "VIEW_SELF", "EDIT_SELF",
    "VOTACAO_VOTAR"
  ],

  FILIADO: [
    "VIEW_SELF", "EDIT_SELF",
    "VOTACAO_VOTAR"
  ]
};
